development:
  FACEBOOK_APP_ID: 373546769386190
  FACEBOOK_APP_SECRET: 02cb9f38727064442c8b9fa8815c88d8
  VK_APP_ID: 3162988
  VK_APP_SECRET: 7w7xzxl3qUqt72xkbFTT
  GOOGLE_APP_ID: 666
  GOOGLE_APP_SECRET: 666
  TWITTER_APP_ID: rShQz1ePwKqOxUehvrcSw
  TWITTER_APP_SECRET: kkfLiPpbaacN2jF7ockL2Guz8NreSs2lECJPcUPW8
  APP_EMAIL_USERNAME: anton.z@randrmusic.com
  APP_EMAIL_PASSWORD: sk2121212121

test:
  FACEBOOK_APP_ID: 373546769386190
  FACEBOOK_APP_SECRET: 02cb9f38727064442c8b9fa8815c88d8
  VK_APP_ID: 3162988
  VK_APP_SECRET: 7w7xzxl3qUqt72xkbFTT
  GOOGLE_APP_ID: 666
  GOOGLE_APP_SECRET: 666
  TWITTER_APP_ID: rShQz1ePwKqOxUehvrcSw
  TWITTER_APP_SECRET: kkfLiPpbaacN2jF7ockL2Guz8NreSs2lECJPcUPW8
  APP_EMAIL_USERNAME: --
  APP_EMAIL_PASSWORD: ---

production:
  FACEBOOK_APP_ID: 378453688902411
  FACEBOOK_APP_SECRET: 17dbe467e5889e108c5384171668bda1
  VK_APP_ID: 3229353
  VK_APP_SECRET: YOpamQsXh2lxNVyYTP0a
  GOOGLE_APP_ID: 666
  GOOGLE_APP_SECRET: 666
  TWITTER_APP_ID: cL9zrZLOYcemJ8nmLJCmCw
  TWITTER_APP_SECRET: 1VRwuXw5ofBSHPbfsvpniVRZd3bzwO5I6rwtF8
  APP_EMAIL_USERNAME: --
  APP_EMAIL_PASSWORD: ---