development:
  FACEBOOK_APP_ID: 373546769386190
  FACEBOOK_APP_SECRET: 02cb9f38727064442c8b9fa8815c88d8
  VK_APP_ID: 3162988
  VK_APP_SECRET: 7w7xzxl3qUqt72xkbFTT
  TWITTER_APP_ID: 3162988
  TWITTER_APP_SECRET: 7w7xzxl3qUqt72xkbFTT
  APP_EMAIL_USERNAME: --
  APP_EMAIL_PASSWORD: ---
  SMS_LOGIN: 'topclub'
  SMS_PASSWORD: '198666'
  SMS_SENDER: 'TOPClub'

test:
  FACEBOOK_APP_ID: 373546769386190
  FACEBOOK_APP_SECRET: 02cb9f38727064442c8b9fa8815c88d8
  VK_APP_ID: 3162988
  VK_APP_SECRET: 7w7xzxl3qUqt72xkbFTT
  TWITTER_APP_ID: J7JQNKFOdbLleAJLdlbqHQ
  TWITTER_APP_SECRET: Oh4fsRhwH1RwEnqRVYUujmCdylXsnjyKShY7jw
  APP_EMAIL_USERNAME: --
  APP_EMAIL_PASSWORD: ---
  SMS_LOGIN: 'topclub'
  SMS_PASSWORD: '198666'
  SMS_SENDER: 'TOPClub'

production:
  FACEBOOK_APP_ID: 453952084669104
  FACEBOOK_APP_SECRET: 5722407bc5c7e1c4138f2bb6a6d0b330
  VK_APP_ID: 3317932
  VK_APP_SECRET: EfegK7C6kTnkBBjYO4mX
  TWITTER_APP_ID: riEWbc18JbFokkC6QuON2g
  TWITTER_APP_SECRET: eF7boMYYSyNl9oPLbmILgB2PMcsCxZHZqt7G3rc5Pw
  APP_EMAIL_USERNAME: --
  APP_EMAIL_PASSWORD: ---
  SMS_LOGIN: 'topclub'
  SMS_PASSWORD: '198666'
  SMS_SENDER: 'TOPClub'