:user:
  :resource: false
  :collection: true
  :is_own: true
  :model: User
:place:
  :resource: true
  :collection: true
  :is_own: true
  :model: Place

:reservation:
  :resource: false
  :collection: true
  :is_own: true
  :is_visibility: true
  :model: Reservation
  :assocs: [:place]