:user:
  :resource: false
  :collection: true
  :is_own: true
  :model: User
:reservation:
  :resource: false
  :collection: true
  :is_own: true
  :is_visibility: true
  :model: Reservation
  :assocs: [:place]

:place:
  :resource: true
  :collection: false
  :is_own: true
  :model: Place