#:locator:
#  :resource: false
#  :collection: true
#  :model: Locator
#  :collection_actions: [:update]
#:configuration:
#  :resource: false
#  :collection: true
#  :model: Configuration
#  :collection_actions: [:update]
:category:
  :resource: true
  :collection: true
  :is_own: true
  :model: Category
  :collection_actions: [:read, :create, :update, :delete]
  :member_actions: [:read, :update, :delete, :rebuild]
:user:
  :resource: false
  :collection: true
  :is_own: true
  :model: User
  :assocs: [:groups]
#:group:
#  :resource: true
#  :collection: true
#  :is_own: true
#  :model: Group
#:role:
#  :resource: false
#  :collection: true
#  :is_own: true
#  :model: Role
:structure:
  :resource: true
  :collection: true
  :is_own: true
  :is_visibility: true
  :model: Structure
:static_page:
  :resource: true
  :collection: true
  :is_own: true
  :is_visibility: true
  :model: StaticPage
  :assocs: [:structure]