generate_autocomplete:
  cron: "30 3 * * *"
  class: GenerateAutocompleteJob
  queue: low
  description: "This generate autocomplete"
elastic_indexer:
  cron: "0 5 * * *"
  class: ElasticIndexerJob
  queue: high
  description: "This update elastic index"
send_sms:
  cron: "0 10,12,14,16,18,20 * * *"
  class: SendSmsJob
  queue: low
  description: "This send sms for reserve done"
site_map:
  cron: "0 4 * * *"
  class: SiteMapJob
  queue: low
  description: "This update site map"
